#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-nocaselist
Version  : 1.0.4
Release  : 19
URL      : https://files.pythonhosted.org/packages/fe/5c/bfb5a421027852e577491ebfa6f9e454066bd430b4b7007692776c45da62/nocaselist-1.0.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/fe/5c/bfb5a421027852e577491ebfa6f9e454066bd430b4b7007692776c45da62/nocaselist-1.0.4.tar.gz
Summary  : A case-insensitive list for Python
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-nocaselist-license = %{version}-%{release}
Requires: pypi-nocaselist-python = %{version}-%{release}
Requires: pypi-nocaselist-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: nocaselist
Provides: nocaselist-python
Provides: nocaselist-python3

%description
===============================================

%package license
Summary: license components for the pypi-nocaselist package.
Group: Default

%description license
license components for the pypi-nocaselist package.


%package python
Summary: python components for the pypi-nocaselist package.
Group: Default
Requires: pypi-nocaselist-python3 = %{version}-%{release}

%description python
python components for the pypi-nocaselist package.


%package python3
Summary: python3 components for the pypi-nocaselist package.
Group: Default
Requires: python3-core
Provides: pypi(nocaselist)

%description python3
python3 components for the pypi-nocaselist package.


%prep
%setup -q -n nocaselist-1.0.4
cd %{_builddir}/nocaselist-1.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641459349
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-nocaselist
cp %{_builddir}/nocaselist-1.0.4/LICENSE %{buildroot}/usr/share/package-licenses/pypi-nocaselist/b314c7ebb7d599944981908b7f3ed33a30e78f3a
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-nocaselist/b314c7ebb7d599944981908b7f3ed33a30e78f3a

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
